FILE_PATH = ""
APP_ENV = 'production'
FILE_PATH = "/home/lbprod/serverApplication/FileStore/error_files/"
PROCESSED_FILE_PATH = "/home/lbprod/serverApplication/FileStore/processed_files/"
SENTRY_DSN="https://808c9472a8e349a5a789c66d2dde9f9f@sentry.io/3790190"
SEARCH_ENGINE_BASE_URL="http://localhost:8555/api/"
SEARCH_ENGINE_GET_QUESTION_URL="questions/all"
SEARCH_ENGINE_GET_SKILL_SET_URL="data/getSkillNameList"
NEO4J_URL="bolt://localhost:7687"
PORT=5000